apiVersion: v1
kind: Secret
metadata:
  name: fog-msrv-waap-tuning-process-secret
data:
  DATATUBE_WAAP_DATASET_ID: {{ .Values.datatubeWaapDatasetId | b64enc }}
  DATATUBE_SERVICE_ACCOUNT_JSON: {{ .Values.datatubeServiceAccountJson | quote | b64enc }}
