apiVersion: apps/v1
kind: Deployment
metadata:
  name: fog-msrv-waap-tuning-process-deployment
  labels:
    app: fog-msrv-waap-tuning-process-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fog-msrv-waap-tuning-process-lbl
  template:
    metadata:
      labels:
        app: fog-msrv-waap-tuning-process-lbl
    spec:
      containers:
        - name:  fog-msrv-waap-tuning-processing
          imagePullPolicy: Always
          image: 342930366839.dkr.ecr.eu-west-1.amazonaws.com/fog-msrv-waap-tuning-processing:{{ .Values.image_tag }}
          ports:
            - containerPort: 8080
          env:
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: TRACER_HOST
              value: jaeger-agent
            - name: TRACER_PORT
              value: '6831'
            - name: TRACER_SAMPLE_RATE
              value: '1.0'
            - name: TRACER_ENABLED
              value: 'false'
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 5
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /health/ready
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 3
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
