apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v2
      kind: Mapping
      name: tuningServiceProcess_mapping
      prefix: /tuningServiceProcess/
      rewrite: /
      bypass_auth: false
      service: fog-msrv-waap-tuning-process-svc:80
      ambassador_id: ["ambassador-upstream", "ambassador-downstream"]
      ---
  name: fog-msrv-waap-tuning-process-svc
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 8080
    - name: "https"
      port: 443
      targetPort: 8080
  selector:
    app: fog-msrv-waap-tuning-process-lbl

